// <auto-generated />
namespace EatmEntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NameLengthAnnotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameLengthAnnotation));
        
        string IMigrationMetadata.Id
        {
            get { return "201801271910284_NameLengthAnnotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
